services:
  modu-next:
    container_name: modu-next
    restart: always
    image: node:20
    ports:
      - '3000-3000'
    environment:
      - PORT=3000
    volumes:
      - ./:/usr/src/modu-next
    working_dir: /usr/src/modu-next

    networks:
      - client-network
    # FOR PRODUCTION
    command: bash -c "yarn && yarn run build && yarn run start"

networks:
  client-network:
    driver: bridge
